-- ACESSOS-01 — RLS POR TENANT. `tenant_ok(cliente)` = admin AgroinBlue OU membro ativo daquele cliente.
-- 82 tabelas com `cliente_id` x 4 policies (select/insert/update/delete); 4 tabelas de REFERENCIA ficam
--   com leitura livre e escrita so' admin; `profiles` ve' a propria linha; 10 filhas sem `cliente_id`
--   filtram pelo pai. Plano de contas e parametros de nutricao com `cliente_id` NULO seguem legiveis (globais).
-- ACESSOS-01: RLS por tenant nas tabelas com policy aberta (true)
create or replace function public.tenant_ok(_cliente uuid) returns boolean language sql stable security definer set search_path = public as $$
  select public.is_admin_agroinblue((select auth.uid())) or (_cliente is not null and _cliente in (select public.get_user_cliente_ids((select auth.uid()))))
$$;
revoke all on function public.tenant_ok(uuid) from public; grant execute on function public.tenant_ok(uuid) to authenticated;
drop policy if exists "agri_barter_contratos_delete_open" on public.agri_barter_contratos;
drop policy if exists "agri_barter_contratos_insert_open" on public.agri_barter_contratos;
drop policy if exists "agri_barter_contratos_select_open" on public.agri_barter_contratos;
drop policy if exists "agri_barter_contratos_update_open" on public.agri_barter_contratos;
drop policy if exists "agri_colheita_delete_open" on public.agri_colheita;
drop policy if exists "agri_colheita_insert_open" on public.agri_colheita;
drop policy if exists "agri_colheita_select_open" on public.agri_colheita;
drop policy if exists "agri_colheita_update_open" on public.agri_colheita;
drop policy if exists "agri_contratos_armazenagem_delete_open" on public.agri_contratos_armazenagem;
drop policy if exists "agri_contratos_armazenagem_insert_open" on public.agri_contratos_armazenagem;
drop policy if exists "agri_contratos_armazenagem_select_open" on public.agri_contratos_armazenagem;
drop policy if exists "agri_contratos_armazenagem_update_open" on public.agri_contratos_armazenagem;
drop policy if exists "agri_cotacao_graos_delete_open" on public.agri_cotacao_graos;
drop policy if exists "agri_cotacao_graos_insert_open" on public.agri_cotacao_graos;
drop policy if exists "agri_cotacao_graos_select_open" on public.agri_cotacao_graos;
drop policy if exists "agri_cotacao_graos_update_open" on public.agri_cotacao_graos;
drop policy if exists "agri_estoque_movimentacoes_delete_open" on public.agri_estoque_movimentacoes;
drop policy if exists "agri_estoque_movimentacoes_insert_open" on public.agri_estoque_movimentacoes;
drop policy if exists "agri_estoque_movimentacoes_select_open" on public.agri_estoque_movimentacoes;
drop policy if exists "agri_estoque_movimentacoes_update_open" on public.agri_estoque_movimentacoes;
drop policy if exists "agri_locais_estoque_delete_open" on public.agri_locais_estoque;
drop policy if exists "agri_locais_estoque_insert_open" on public.agri_locais_estoque;
drop policy if exists "agri_locais_estoque_select_open" on public.agri_locais_estoque;
drop policy if exists "agri_locais_estoque_update_open" on public.agri_locais_estoque;
drop policy if exists "agri_oc_entregas_delete_open" on public.agri_oc_entregas;
drop policy if exists "agri_oc_entregas_insert_open" on public.agri_oc_entregas;
drop policy if exists "agri_oc_entregas_select_open" on public.agri_oc_entregas;
drop policy if exists "agri_oc_entregas_update_open" on public.agri_oc_entregas;
drop policy if exists "agri_oc_insumos_delete_open" on public.agri_oc_insumos;
drop policy if exists "agri_oc_insumos_insert_open" on public.agri_oc_insumos;
drop policy if exists "agri_oc_insumos_select_open" on public.agri_oc_insumos;
drop policy if exists "agri_oc_insumos_update_open" on public.agri_oc_insumos;
drop policy if exists "agri_oc_partes_delete_open" on public.agri_oc_partes;
drop policy if exists "agri_oc_partes_insert_open" on public.agri_oc_partes;
drop policy if exists "agri_oc_partes_select_open" on public.agri_oc_partes;
drop policy if exists "agri_oc_partes_update_open" on public.agri_oc_partes;
drop policy if exists "agri_operacoes_comerciais_delete_open" on public.agri_operacoes_comerciais;
drop policy if exists "agri_operacoes_comerciais_insert_open" on public.agri_operacoes_comerciais;
drop policy if exists "agri_operacoes_comerciais_select_open" on public.agri_operacoes_comerciais;
drop policy if exists "agri_operacoes_comerciais_update_open" on public.agri_operacoes_comerciais;
drop policy if exists "agri_rateio_admin_delete_open" on public.agri_rateio_admin;
drop policy if exists "agri_rateio_admin_insert_open" on public.agri_rateio_admin;
drop policy if exists "agri_rateio_admin_select_open" on public.agri_rateio_admin;
drop policy if exists "agri_rateio_admin_update_open" on public.agri_rateio_admin;
drop policy if exists "agri_safra_area_delete_open" on public.agri_safra_area;
drop policy if exists "agri_safra_area_insert_open" on public.agri_safra_area;
drop policy if exists "agri_safra_area_select_open" on public.agri_safra_area;
drop policy if exists "agri_safra_area_update_open" on public.agri_safra_area;
drop policy if exists "analise_consultor_all" on public.analise_consultor;
drop policy if exists "audit_log_all" on public.audit_log;
drop policy if exists "audit_log_movimentacoes_all" on public.audit_log_movimentacoes;
drop policy if exists "bancos_leitura_publica" on public.bancos_referencia;
drop policy if exists "boitel_adiantamentos_all" on public.boitel_adiantamentos;
drop policy if exists "boitel_lotes_all" on public.boitel_lotes;
drop policy if exists "boitel_operacoes_all" on public.boitel_operacoes;
drop policy if exists "boitel_planejamento_all" on public.boitel_planejamento;
drop policy if exists "boitel_planejamento_historico_all" on public.boitel_planejamento_historico;
drop policy if exists "categorias_select_open" on public.categorias;
drop policy if exists "cr_sel" on public.categorias_rebanho;
drop policy if exists "cfg_categoria_parametros_all" on public.cfg_categoria_parametros;
drop policy if exists "chuvas_delete_open" on public.chuvas;
drop policy if exists "chuvas_insert_open" on public.chuvas;
drop policy if exists "chuvas_select_open" on public.chuvas;
drop policy if exists "chuvas_update_open" on public.chuvas;
drop policy if exists "competencia_fechamento_all" on public.competencia_fechamento;
drop policy if exists "excel_aux_delete" on public.excel_linhas_aux;
drop policy if exists "excel_aux_insert" on public.excel_linhas_aux;
drop policy if exists "excel_aux_select" on public.excel_linhas_aux;
drop policy if exists "excel_aux_update" on public.excel_linhas_aux;
drop policy if exists "fazenda_cadastros_all" on public.fazenda_cadastros;
drop policy if exists "fazenda_status_mensal_all" on public.fazenda_status_mensal;
drop policy if exists "fechamento_execucoes_all" on public.fechamento_execucoes;
drop policy if exists "fechamento_executivo_all" on public.fechamento_executivo;
drop policy if exists "fechamento_graficos_all" on public.fechamento_graficos;
drop policy if exists "fechamento_indicadores_all" on public.fechamento_indicadores;
drop policy if exists "fechamento_pasto_itens_delete_open" on public.fechamento_pasto_itens;
drop policy if exists "fechamento_pasto_itens_insert_open" on public.fechamento_pasto_itens;
drop policy if exists "fechamento_pasto_itens_select_open" on public.fechamento_pasto_itens;
drop policy if exists "fechamento_pasto_itens_update_open" on public.fechamento_pasto_itens;
drop policy if exists "fechamento_pastos_insert_open" on public.fechamento_pastos;
drop policy if exists "fechamento_pastos_select_open" on public.fechamento_pastos;
drop policy if exists "fechamento_pastos_update_open" on public.fechamento_pastos;
drop policy if exists "fechamento_reaberturas_log_all" on public.fechamento_reaberturas_log;
drop policy if exists "fechamento_textos_all" on public.fechamento_textos;
drop policy if exists "fechamentos_executivos_all" on public.fechamentos_executivos;
drop policy if exists "fcc_ins" on public.financeiro_centros_custo;
drop policy if exists "fcc_sel" on public.financeiro_centros_custo;
drop policy if exists "financeiro_classificacao_regras_all" on public.financeiro_classificacao_regras;
drop policy if exists "financeiro_conciliacoes_all" on public.financeiro_conciliacoes;
drop policy if exists "financeiro_contas_all" on public.financeiro_contas;
drop policy if exists "fd_sel" on public.financeiro_dividendos;
drop policy if exists "fin_dividendos_delete" on public.financeiro_dividendos;
drop policy if exists "fin_dividendos_insert" on public.financeiro_dividendos;
drop policy if exists "fin_dividendos_update" on public.financeiro_dividendos;
drop policy if exists "financeiro_duplicidade_log_all" on public.financeiro_duplicidade_log;
drop policy if exists "financeiro_extrato_bancario_all" on public.financeiro_extrato_bancario;
drop policy if exists "fin_fech_insert" on public.financeiro_fechamentos;
drop policy if exists "fin_fech_select" on public.financeiro_fechamentos;
drop policy if exists "financeiro_fornecedores_select_open" on public.financeiro_fornecedores;
drop policy if exists "forn_delete" on public.financeiro_fornecedores;
drop policy if exists "forn_insert" on public.financeiro_fornecedores;
drop policy if exists "forn_select" on public.financeiro_fornecedores;
drop policy if exists "forn_update" on public.financeiro_fornecedores;
drop policy if exists "fornecedores_all" on public.financeiro_fornecedores;
drop policy if exists "financeiro_importacoes_all" on public.financeiro_importacoes;
drop policy if exists "fiv_ins" on public.financeiro_importacoes_v2;
drop policy if exists "fiv_sel" on public.financeiro_importacoes_v2;
drop policy if exists "fiv_upd" on public.financeiro_importacoes_v2;
drop policy if exists "financeiro_lancamentos_all" on public.financeiro_lancamentos;
drop policy if exists "financeiro_mapa_classificacao_all" on public.financeiro_mapa_classificacao;
drop policy if exists "fpc_ins" on public.financeiro_plano_contas;
drop policy if exists "fpc_sel" on public.financeiro_plano_contas;
drop policy if exists "fpc_upd" on public.financeiro_plano_contas;
drop policy if exists "plano_insert" on public.financeiro_plano_contas;
drop policy if exists "plano_select" on public.financeiro_plano_contas;
drop policy if exists "financeiro_rateio_adm_all" on public.financeiro_rateio_adm;
drop policy if exists "financeiro_rateio_adm_itens_all" on public.financeiro_rateio_adm_itens;
drop policy if exists "financeiro_resumo_caixa_all" on public.financeiro_resumo_caixa;
drop policy if exists "audit_all" on public.financeiro_saldos_audit;
drop policy if exists "financeiro_saldos_bancarios_select_open" on public.financeiro_saldos_bancarios;
drop policy if exists "fin_saldos_insert" on public.financeiro_saldos_bancarios_v2;
drop policy if exists "fin_saldos_select" on public.financeiro_saldos_bancarios_v2;
drop policy if exists "fin_saldos_update" on public.financeiro_saldos_bancarios_v2;
drop policy if exists "alias_all_service_role" on public.financeiro_subcentro_aliases;
drop policy if exists "alias_insert_public" on public.financeiro_subcentro_aliases;
drop policy if exists "alias_select_authenticated" on public.financeiro_subcentro_aliases;
drop policy if exists "alias_select_public" on public.financeiro_subcentro_aliases;
drop policy if exists "alias_update_public" on public.financeiro_subcentro_aliases;
drop policy if exists "financeiros_select_open" on public.financeiros;
drop policy if exists "lancamentos_insert_open" on public.lancamentos;
drop policy if exists "lancamentos_select_open" on public.lancamentos;
drop policy if exists "lancamentos_update_open" on public.lancamentos;
drop policy if exists "mesa_lancamento_staging_all" on public.mesa_lancamento_staging;
drop policy if exists "mesa_ofx_validacao_all" on public.mesa_ofx_validacao;
drop policy if exists "mesa_par_all" on public.mesa_par;
drop policy if exists "mesa_sessao_all" on public.mesa_sessao;
drop policy if exists "meta_aprovacoes_all" on public.meta_aprovacoes;
drop policy if exists "mgmd_ins" on public.meta_gmd_mensal;
drop policy if exists "mgmd_sel" on public.meta_gmd_mensal;
drop policy if exists "mgmd_upd" on public.meta_gmd_mensal;
drop policy if exists "meta_nutricao_all" on public.meta_parametros_nutricao;
drop policy if exists "meta_preco_mercado_all" on public.meta_preco_mercado;
drop policy if exists "meta_preco_mercado_status_all" on public.meta_preco_mercado_status;
drop policy if exists "meta_projetos_all" on public.meta_projetos_investimento;
drop policy if exists "mvr_all" on public.meta_valor_rebanho_precos;
drop policy if exists "mvrs_all" on public.meta_valor_rebanho_status;
drop policy if exists "meta_versoes_all" on public.meta_versoes;
drop policy if exists "pasto_condicoes_all" on public.pasto_condicoes;
drop policy if exists "pasto_geometrias_all" on public.pasto_geometrias;
drop policy if exists "pasto_movimentacoes_all" on public.pasto_movimentacoes;
drop policy if exists "pastos_insert_open" on public.pastos;
drop policy if exists "pastos_select_open" on public.pastos;
drop policy if exists "pastos_update_open" on public.pastos;
drop policy if exists "areas_meta_delete" on public.planejamento_area_meta;
drop policy if exists "areas_meta_insert" on public.planejamento_area_meta;
drop policy if exists "areas_meta_select" on public.planejamento_area_meta;
drop policy if exists "areas_meta_update" on public.planejamento_area_meta;
drop policy if exists "planejamento_delete" on public.planejamento_financeiro;
drop policy if exists "planejamento_insert" on public.planejamento_financeiro;
drop policy if exists "planejamento_select" on public.planejamento_financeiro;
drop policy if exists "planejamento_update" on public.planejamento_financeiro;
drop policy if exists "preco_mercado_all" on public.preco_mercado;
drop policy if exists "preco_mercado_ajuste_select_open" on public.preco_mercado_ajuste;
drop policy if exists "preco_mercado_status_all" on public.preco_mercado_status;
drop policy if exists "profiles_all" on public.profiles;
drop policy if exists "reclassificacoes_select_open" on public.reclassificacoes;
drop policy if exists "saldos_iniciais_insert_open" on public.saldos_iniciais;
drop policy if exists "saldos_iniciais_select_open" on public.saldos_iniciais;
drop policy if exists "saldos_iniciais_update_open" on public.saldos_iniciais;
drop policy if exists "valor_rebanho_fechamento_select_open" on public.valor_rebanho_fechamento;
drop policy if exists "vrf_del" on public.valor_rebanho_fechamento;
drop policy if exists "vrf_ins" on public.valor_rebanho_fechamento;
drop policy if exists "vrf_sel" on public.valor_rebanho_fechamento;
drop policy if exists "vrf_upd" on public.valor_rebanho_fechamento;
drop policy if exists "vrfi_del" on public.valor_rebanho_fechamento_itens;
drop policy if exists "vrfi_ins" on public.valor_rebanho_fechamento_itens;
drop policy if exists "vrfi_sel" on public.valor_rebanho_fechamento_itens;
drop policy if exists "vrfi_upd" on public.valor_rebanho_fechamento_itens;
drop policy if exists "valor_rebanho_mensal_select_open" on public.valor_rebanho_mensal;
drop policy if exists "vrm_del" on public.valor_rebanho_mensal;
drop policy if exists "vrm_ins" on public.valor_rebanho_mensal;
drop policy if exists "vrm_sel" on public.valor_rebanho_mensal;
drop policy if exists "vrm_upd" on public.valor_rebanho_mensal;
drop policy if exists "vrm_all" on public.valor_rebanho_meta;
drop policy if exists "vrmi_all" on public.valor_rebanho_meta_itens;
drop policy if exists "vrmv_all" on public.valor_rebanho_meta_validada;
drop policy if exists "vrv_all" on public.valor_rebanho_realizado_validado;
drop policy if exists "zoo_componentes_financeiros_select" on public.zoo_componentes_financeiros;
drop policy if exists "zoot_importacoes_all" on public.zoot_importacoes;
drop policy if exists "zoot_importacoes_staging_all" on public.zoot_importacoes_staging;
drop policy if exists "zoot_mensal_cache_all" on public.zoot_mensal_cache;
create policy agri_barter_contratos_select_tenant on public.agri_barter_contratos for select to authenticated using (public.tenant_ok(cliente_id));
create policy agri_barter_contratos_insert_tenant on public.agri_barter_contratos for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy agri_barter_contratos_update_tenant on public.agri_barter_contratos for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy agri_barter_contratos_delete_tenant on public.agri_barter_contratos for delete to authenticated using (public.tenant_ok(cliente_id));
create policy agri_colheita_select_tenant on public.agri_colheita for select to authenticated using (public.tenant_ok(cliente_id));
create policy agri_colheita_insert_tenant on public.agri_colheita for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy agri_colheita_update_tenant on public.agri_colheita for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy agri_colheita_delete_tenant on public.agri_colheita for delete to authenticated using (public.tenant_ok(cliente_id));
create policy agri_contratos_armazenagem_select_tenant on public.agri_contratos_armazenagem for select to authenticated using (public.tenant_ok(cliente_id));
create policy agri_contratos_armazenagem_insert_tenant on public.agri_contratos_armazenagem for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy agri_contratos_armazenagem_update_tenant on public.agri_contratos_armazenagem for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy agri_contratos_armazenagem_delete_tenant on public.agri_contratos_armazenagem for delete to authenticated using (public.tenant_ok(cliente_id));
create policy agri_cotacao_graos_select_tenant on public.agri_cotacao_graos for select to authenticated using (public.tenant_ok(cliente_id));
create policy agri_cotacao_graos_insert_tenant on public.agri_cotacao_graos for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy agri_cotacao_graos_update_tenant on public.agri_cotacao_graos for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy agri_cotacao_graos_delete_tenant on public.agri_cotacao_graos for delete to authenticated using (public.tenant_ok(cliente_id));
create policy agri_estoque_movimentacoes_select_tenant on public.agri_estoque_movimentacoes for select to authenticated using (public.tenant_ok(cliente_id));
create policy agri_estoque_movimentacoes_insert_tenant on public.agri_estoque_movimentacoes for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy agri_estoque_movimentacoes_update_tenant on public.agri_estoque_movimentacoes for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy agri_estoque_movimentacoes_delete_tenant on public.agri_estoque_movimentacoes for delete to authenticated using (public.tenant_ok(cliente_id));
create policy agri_locais_estoque_select_tenant on public.agri_locais_estoque for select to authenticated using (public.tenant_ok(cliente_id));
create policy agri_locais_estoque_insert_tenant on public.agri_locais_estoque for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy agri_locais_estoque_update_tenant on public.agri_locais_estoque for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy agri_locais_estoque_delete_tenant on public.agri_locais_estoque for delete to authenticated using (public.tenant_ok(cliente_id));
create policy agri_oc_entregas_select_tenant on public.agri_oc_entregas for select to authenticated using (public.tenant_ok(cliente_id));
create policy agri_oc_entregas_insert_tenant on public.agri_oc_entregas for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy agri_oc_entregas_update_tenant on public.agri_oc_entregas for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy agri_oc_entregas_delete_tenant on public.agri_oc_entregas for delete to authenticated using (public.tenant_ok(cliente_id));
create policy agri_oc_insumos_select_tenant on public.agri_oc_insumos for select to authenticated using (public.tenant_ok(cliente_id));
create policy agri_oc_insumos_insert_tenant on public.agri_oc_insumos for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy agri_oc_insumos_update_tenant on public.agri_oc_insumos for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy agri_oc_insumos_delete_tenant on public.agri_oc_insumos for delete to authenticated using (public.tenant_ok(cliente_id));
create policy agri_oc_partes_select_tenant on public.agri_oc_partes for select to authenticated using (public.tenant_ok(cliente_id));
create policy agri_oc_partes_insert_tenant on public.agri_oc_partes for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy agri_oc_partes_update_tenant on public.agri_oc_partes for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy agri_oc_partes_delete_tenant on public.agri_oc_partes for delete to authenticated using (public.tenant_ok(cliente_id));
create policy agri_operacoes_comerciais_select_tenant on public.agri_operacoes_comerciais for select to authenticated using (public.tenant_ok(cliente_id));
create policy agri_operacoes_comerciais_insert_tenant on public.agri_operacoes_comerciais for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy agri_operacoes_comerciais_update_tenant on public.agri_operacoes_comerciais for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy agri_operacoes_comerciais_delete_tenant on public.agri_operacoes_comerciais for delete to authenticated using (public.tenant_ok(cliente_id));
create policy agri_rateio_admin_select_tenant on public.agri_rateio_admin for select to authenticated using (public.tenant_ok(cliente_id));
create policy agri_rateio_admin_insert_tenant on public.agri_rateio_admin for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy agri_rateio_admin_update_tenant on public.agri_rateio_admin for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy agri_rateio_admin_delete_tenant on public.agri_rateio_admin for delete to authenticated using (public.tenant_ok(cliente_id));
create policy agri_safra_area_select_tenant on public.agri_safra_area for select to authenticated using (public.tenant_ok(cliente_id));
create policy agri_safra_area_insert_tenant on public.agri_safra_area for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy agri_safra_area_update_tenant on public.agri_safra_area for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy agri_safra_area_delete_tenant on public.agri_safra_area for delete to authenticated using (public.tenant_ok(cliente_id));
create policy analise_consultor_select_tenant on public.analise_consultor for select to authenticated using (public.tenant_ok(cliente_id));
create policy analise_consultor_insert_tenant on public.analise_consultor for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy analise_consultor_update_tenant on public.analise_consultor for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy analise_consultor_delete_tenant on public.analise_consultor for delete to authenticated using (public.tenant_ok(cliente_id));
create policy audit_log_select_tenant on public.audit_log for select to authenticated using (public.tenant_ok(cliente_id));
create policy audit_log_insert_tenant on public.audit_log for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy audit_log_update_tenant on public.audit_log for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy audit_log_delete_tenant on public.audit_log for delete to authenticated using (public.tenant_ok(cliente_id));
create policy audit_log_movimentacoes_select_tenant on public.audit_log_movimentacoes for select to authenticated using (public.tenant_ok(cliente_id));
create policy audit_log_movimentacoes_insert_tenant on public.audit_log_movimentacoes for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy audit_log_movimentacoes_update_tenant on public.audit_log_movimentacoes for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy audit_log_movimentacoes_delete_tenant on public.audit_log_movimentacoes for delete to authenticated using (public.tenant_ok(cliente_id));
create policy boitel_adiantamentos_select_tenant on public.boitel_adiantamentos for select to authenticated using (public.tenant_ok(cliente_id));
create policy boitel_adiantamentos_insert_tenant on public.boitel_adiantamentos for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy boitel_adiantamentos_update_tenant on public.boitel_adiantamentos for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy boitel_adiantamentos_delete_tenant on public.boitel_adiantamentos for delete to authenticated using (public.tenant_ok(cliente_id));
create policy boitel_lotes_select_tenant on public.boitel_lotes for select to authenticated using (public.tenant_ok(cliente_id));
create policy boitel_lotes_insert_tenant on public.boitel_lotes for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy boitel_lotes_update_tenant on public.boitel_lotes for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy boitel_lotes_delete_tenant on public.boitel_lotes for delete to authenticated using (public.tenant_ok(cliente_id));
create policy boitel_operacoes_select_tenant on public.boitel_operacoes for select to authenticated using (public.tenant_ok(cliente_id));
create policy boitel_operacoes_insert_tenant on public.boitel_operacoes for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy boitel_operacoes_update_tenant on public.boitel_operacoes for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy boitel_operacoes_delete_tenant on public.boitel_operacoes for delete to authenticated using (public.tenant_ok(cliente_id));
create policy boitel_planejamento_select_tenant on public.boitel_planejamento for select to authenticated using (public.tenant_ok(cliente_id));
create policy boitel_planejamento_insert_tenant on public.boitel_planejamento for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy boitel_planejamento_update_tenant on public.boitel_planejamento for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy boitel_planejamento_delete_tenant on public.boitel_planejamento for delete to authenticated using (public.tenant_ok(cliente_id));
create policy cfg_categoria_parametros_select_tenant on public.cfg_categoria_parametros for select to authenticated using (public.tenant_ok(cliente_id));
create policy cfg_categoria_parametros_insert_tenant on public.cfg_categoria_parametros for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy cfg_categoria_parametros_update_tenant on public.cfg_categoria_parametros for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy cfg_categoria_parametros_delete_tenant on public.cfg_categoria_parametros for delete to authenticated using (public.tenant_ok(cliente_id));
create policy chuvas_select_tenant on public.chuvas for select to authenticated using (public.tenant_ok(cliente_id));
create policy chuvas_insert_tenant on public.chuvas for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy chuvas_update_tenant on public.chuvas for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy chuvas_delete_tenant on public.chuvas for delete to authenticated using (public.tenant_ok(cliente_id));
create policy competencia_fechamento_select_tenant on public.competencia_fechamento for select to authenticated using (public.tenant_ok(cliente_id));
create policy competencia_fechamento_insert_tenant on public.competencia_fechamento for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy competencia_fechamento_update_tenant on public.competencia_fechamento for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy competencia_fechamento_delete_tenant on public.competencia_fechamento for delete to authenticated using (public.tenant_ok(cliente_id));
create policy excel_linhas_aux_select_tenant on public.excel_linhas_aux for select to authenticated using (public.tenant_ok(cliente_id));
create policy excel_linhas_aux_insert_tenant on public.excel_linhas_aux for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy excel_linhas_aux_update_tenant on public.excel_linhas_aux for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy excel_linhas_aux_delete_tenant on public.excel_linhas_aux for delete to authenticated using (public.tenant_ok(cliente_id));
create policy fazenda_cadastros_select_tenant on public.fazenda_cadastros for select to authenticated using (public.tenant_ok(cliente_id));
create policy fazenda_cadastros_insert_tenant on public.fazenda_cadastros for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy fazenda_cadastros_update_tenant on public.fazenda_cadastros for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy fazenda_cadastros_delete_tenant on public.fazenda_cadastros for delete to authenticated using (public.tenant_ok(cliente_id));
create policy fazenda_status_mensal_select_tenant on public.fazenda_status_mensal for select to authenticated using (public.tenant_ok(cliente_id));
create policy fazenda_status_mensal_insert_tenant on public.fazenda_status_mensal for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy fazenda_status_mensal_update_tenant on public.fazenda_status_mensal for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy fazenda_status_mensal_delete_tenant on public.fazenda_status_mensal for delete to authenticated using (public.tenant_ok(cliente_id));
create policy fechamento_execucoes_select_tenant on public.fechamento_execucoes for select to authenticated using (public.tenant_ok(cliente_id));
create policy fechamento_execucoes_insert_tenant on public.fechamento_execucoes for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy fechamento_execucoes_update_tenant on public.fechamento_execucoes for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy fechamento_execucoes_delete_tenant on public.fechamento_execucoes for delete to authenticated using (public.tenant_ok(cliente_id));
create policy fechamento_executivo_select_tenant on public.fechamento_executivo for select to authenticated using (public.tenant_ok(cliente_id));
create policy fechamento_executivo_insert_tenant on public.fechamento_executivo for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy fechamento_executivo_update_tenant on public.fechamento_executivo for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy fechamento_executivo_delete_tenant on public.fechamento_executivo for delete to authenticated using (public.tenant_ok(cliente_id));
create policy fechamento_graficos_select_tenant on public.fechamento_graficos for select to authenticated using (public.tenant_ok(cliente_id));
create policy fechamento_graficos_insert_tenant on public.fechamento_graficos for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy fechamento_graficos_update_tenant on public.fechamento_graficos for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy fechamento_graficos_delete_tenant on public.fechamento_graficos for delete to authenticated using (public.tenant_ok(cliente_id));
create policy fechamento_indicadores_select_tenant on public.fechamento_indicadores for select to authenticated using (public.tenant_ok(cliente_id));
create policy fechamento_indicadores_insert_tenant on public.fechamento_indicadores for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy fechamento_indicadores_update_tenant on public.fechamento_indicadores for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy fechamento_indicadores_delete_tenant on public.fechamento_indicadores for delete to authenticated using (public.tenant_ok(cliente_id));
create policy fechamento_pastos_select_tenant on public.fechamento_pastos for select to authenticated using (public.tenant_ok(cliente_id));
create policy fechamento_pastos_insert_tenant on public.fechamento_pastos for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy fechamento_pastos_update_tenant on public.fechamento_pastos for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy fechamento_pastos_delete_tenant on public.fechamento_pastos for delete to authenticated using (public.tenant_ok(cliente_id));
create policy fechamento_reaberturas_log_select_tenant on public.fechamento_reaberturas_log for select to authenticated using (public.tenant_ok(cliente_id));
create policy fechamento_reaberturas_log_insert_tenant on public.fechamento_reaberturas_log for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy fechamento_reaberturas_log_update_tenant on public.fechamento_reaberturas_log for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy fechamento_reaberturas_log_delete_tenant on public.fechamento_reaberturas_log for delete to authenticated using (public.tenant_ok(cliente_id));
create policy fechamento_textos_select_tenant on public.fechamento_textos for select to authenticated using (public.tenant_ok(cliente_id));
create policy fechamento_textos_insert_tenant on public.fechamento_textos for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy fechamento_textos_update_tenant on public.fechamento_textos for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy fechamento_textos_delete_tenant on public.fechamento_textos for delete to authenticated using (public.tenant_ok(cliente_id));
create policy fechamentos_executivos_select_tenant on public.fechamentos_executivos for select to authenticated using (public.tenant_ok(cliente_id));
create policy fechamentos_executivos_insert_tenant on public.fechamentos_executivos for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy fechamentos_executivos_update_tenant on public.fechamentos_executivos for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy fechamentos_executivos_delete_tenant on public.fechamentos_executivos for delete to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_centros_custo_select_tenant on public.financeiro_centros_custo for select to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_centros_custo_insert_tenant on public.financeiro_centros_custo for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy financeiro_centros_custo_update_tenant on public.financeiro_centros_custo for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy financeiro_centros_custo_delete_tenant on public.financeiro_centros_custo for delete to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_classificacao_regras_select_tenant on public.financeiro_classificacao_regras for select to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_classificacao_regras_insert_tenant on public.financeiro_classificacao_regras for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy financeiro_classificacao_regras_update_tenant on public.financeiro_classificacao_regras for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy financeiro_classificacao_regras_delete_tenant on public.financeiro_classificacao_regras for delete to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_conciliacoes_select_tenant on public.financeiro_conciliacoes for select to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_conciliacoes_insert_tenant on public.financeiro_conciliacoes for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy financeiro_conciliacoes_update_tenant on public.financeiro_conciliacoes for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy financeiro_conciliacoes_delete_tenant on public.financeiro_conciliacoes for delete to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_contas_select_tenant on public.financeiro_contas for select to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_contas_insert_tenant on public.financeiro_contas for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy financeiro_contas_update_tenant on public.financeiro_contas for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy financeiro_contas_delete_tenant on public.financeiro_contas for delete to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_dividendos_select_tenant on public.financeiro_dividendos for select to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_dividendos_insert_tenant on public.financeiro_dividendos for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy financeiro_dividendos_update_tenant on public.financeiro_dividendos for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy financeiro_dividendos_delete_tenant on public.financeiro_dividendos for delete to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_duplicidade_log_select_tenant on public.financeiro_duplicidade_log for select to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_duplicidade_log_insert_tenant on public.financeiro_duplicidade_log for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy financeiro_duplicidade_log_update_tenant on public.financeiro_duplicidade_log for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy financeiro_duplicidade_log_delete_tenant on public.financeiro_duplicidade_log for delete to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_extrato_bancario_select_tenant on public.financeiro_extrato_bancario for select to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_extrato_bancario_insert_tenant on public.financeiro_extrato_bancario for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy financeiro_extrato_bancario_update_tenant on public.financeiro_extrato_bancario for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy financeiro_extrato_bancario_delete_tenant on public.financeiro_extrato_bancario for delete to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_fechamentos_select_tenant on public.financeiro_fechamentos for select to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_fechamentos_insert_tenant on public.financeiro_fechamentos for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy financeiro_fechamentos_update_tenant on public.financeiro_fechamentos for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy financeiro_fechamentos_delete_tenant on public.financeiro_fechamentos for delete to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_fornecedores_select_tenant on public.financeiro_fornecedores for select to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_fornecedores_insert_tenant on public.financeiro_fornecedores for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy financeiro_fornecedores_update_tenant on public.financeiro_fornecedores for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy financeiro_fornecedores_delete_tenant on public.financeiro_fornecedores for delete to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_importacoes_select_tenant on public.financeiro_importacoes for select to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_importacoes_insert_tenant on public.financeiro_importacoes for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy financeiro_importacoes_update_tenant on public.financeiro_importacoes for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy financeiro_importacoes_delete_tenant on public.financeiro_importacoes for delete to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_importacoes_v2_select_tenant on public.financeiro_importacoes_v2 for select to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_importacoes_v2_insert_tenant on public.financeiro_importacoes_v2 for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy financeiro_importacoes_v2_update_tenant on public.financeiro_importacoes_v2 for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy financeiro_importacoes_v2_delete_tenant on public.financeiro_importacoes_v2 for delete to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_lancamentos_select_tenant on public.financeiro_lancamentos for select to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_lancamentos_insert_tenant on public.financeiro_lancamentos for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy financeiro_lancamentos_update_tenant on public.financeiro_lancamentos for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy financeiro_lancamentos_delete_tenant on public.financeiro_lancamentos for delete to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_mapa_classificacao_select_tenant on public.financeiro_mapa_classificacao for select to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_mapa_classificacao_insert_tenant on public.financeiro_mapa_classificacao for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy financeiro_mapa_classificacao_update_tenant on public.financeiro_mapa_classificacao for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy financeiro_mapa_classificacao_delete_tenant on public.financeiro_mapa_classificacao for delete to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_plano_contas_select_tenant on public.financeiro_plano_contas for select to authenticated using (cliente_id is null or public.tenant_ok(cliente_id));
create policy financeiro_plano_contas_insert_tenant on public.financeiro_plano_contas for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy financeiro_plano_contas_update_tenant on public.financeiro_plano_contas for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy financeiro_plano_contas_delete_tenant on public.financeiro_plano_contas for delete to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_rateio_adm_select_tenant on public.financeiro_rateio_adm for select to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_rateio_adm_insert_tenant on public.financeiro_rateio_adm for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy financeiro_rateio_adm_update_tenant on public.financeiro_rateio_adm for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy financeiro_rateio_adm_delete_tenant on public.financeiro_rateio_adm for delete to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_rateio_adm_itens_select_tenant on public.financeiro_rateio_adm_itens for select to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_rateio_adm_itens_insert_tenant on public.financeiro_rateio_adm_itens for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy financeiro_rateio_adm_itens_update_tenant on public.financeiro_rateio_adm_itens for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy financeiro_rateio_adm_itens_delete_tenant on public.financeiro_rateio_adm_itens for delete to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_resumo_caixa_select_tenant on public.financeiro_resumo_caixa for select to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_resumo_caixa_insert_tenant on public.financeiro_resumo_caixa for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy financeiro_resumo_caixa_update_tenant on public.financeiro_resumo_caixa for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy financeiro_resumo_caixa_delete_tenant on public.financeiro_resumo_caixa for delete to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_saldos_audit_select_tenant on public.financeiro_saldos_audit for select to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_saldos_audit_insert_tenant on public.financeiro_saldos_audit for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy financeiro_saldos_audit_update_tenant on public.financeiro_saldos_audit for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy financeiro_saldos_audit_delete_tenant on public.financeiro_saldos_audit for delete to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_saldos_bancarios_select_tenant on public.financeiro_saldos_bancarios for select to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_saldos_bancarios_insert_tenant on public.financeiro_saldos_bancarios for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy financeiro_saldos_bancarios_update_tenant on public.financeiro_saldos_bancarios for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy financeiro_saldos_bancarios_delete_tenant on public.financeiro_saldos_bancarios for delete to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_saldos_bancarios_v2_select_tenant on public.financeiro_saldos_bancarios_v2 for select to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_saldos_bancarios_v2_insert_tenant on public.financeiro_saldos_bancarios_v2 for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy financeiro_saldos_bancarios_v2_update_tenant on public.financeiro_saldos_bancarios_v2 for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy financeiro_saldos_bancarios_v2_delete_tenant on public.financeiro_saldos_bancarios_v2 for delete to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_subcentro_aliases_select_tenant on public.financeiro_subcentro_aliases for select to authenticated using (public.tenant_ok(cliente_id));
create policy financeiro_subcentro_aliases_insert_tenant on public.financeiro_subcentro_aliases for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy financeiro_subcentro_aliases_update_tenant on public.financeiro_subcentro_aliases for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy financeiro_subcentro_aliases_delete_tenant on public.financeiro_subcentro_aliases for delete to authenticated using (public.tenant_ok(cliente_id));
create policy financeiros_select_tenant on public.financeiros for select to authenticated using (public.tenant_ok(cliente_id));
create policy financeiros_insert_tenant on public.financeiros for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy financeiros_update_tenant on public.financeiros for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy financeiros_delete_tenant on public.financeiros for delete to authenticated using (public.tenant_ok(cliente_id));
create policy lancamentos_select_tenant on public.lancamentos for select to authenticated using (public.tenant_ok(cliente_id));
create policy lancamentos_insert_tenant on public.lancamentos for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy lancamentos_update_tenant on public.lancamentos for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy lancamentos_delete_tenant on public.lancamentos for delete to authenticated using (public.tenant_ok(cliente_id));
create policy mesa_lancamento_staging_select_tenant on public.mesa_lancamento_staging for select to authenticated using (public.tenant_ok(cliente_id));
create policy mesa_lancamento_staging_insert_tenant on public.mesa_lancamento_staging for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy mesa_lancamento_staging_update_tenant on public.mesa_lancamento_staging for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy mesa_lancamento_staging_delete_tenant on public.mesa_lancamento_staging for delete to authenticated using (public.tenant_ok(cliente_id));
create policy mesa_sessao_select_tenant on public.mesa_sessao for select to authenticated using (public.tenant_ok(cliente_id));
create policy mesa_sessao_insert_tenant on public.mesa_sessao for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy mesa_sessao_update_tenant on public.mesa_sessao for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy mesa_sessao_delete_tenant on public.mesa_sessao for delete to authenticated using (public.tenant_ok(cliente_id));
create policy meta_aprovacoes_select_tenant on public.meta_aprovacoes for select to authenticated using (public.tenant_ok(cliente_id));
create policy meta_aprovacoes_insert_tenant on public.meta_aprovacoes for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy meta_aprovacoes_update_tenant on public.meta_aprovacoes for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy meta_aprovacoes_delete_tenant on public.meta_aprovacoes for delete to authenticated using (public.tenant_ok(cliente_id));
create policy meta_gmd_mensal_select_tenant on public.meta_gmd_mensal for select to authenticated using (public.tenant_ok(cliente_id));
create policy meta_gmd_mensal_insert_tenant on public.meta_gmd_mensal for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy meta_gmd_mensal_update_tenant on public.meta_gmd_mensal for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy meta_gmd_mensal_delete_tenant on public.meta_gmd_mensal for delete to authenticated using (public.tenant_ok(cliente_id));
create policy meta_parametros_nutricao_select_tenant on public.meta_parametros_nutricao for select to authenticated using (cliente_id is null or public.tenant_ok(cliente_id));
create policy meta_parametros_nutricao_insert_tenant on public.meta_parametros_nutricao for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy meta_parametros_nutricao_update_tenant on public.meta_parametros_nutricao for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy meta_parametros_nutricao_delete_tenant on public.meta_parametros_nutricao for delete to authenticated using (public.tenant_ok(cliente_id));
create policy meta_preco_mercado_select_tenant on public.meta_preco_mercado for select to authenticated using (public.tenant_ok(cliente_id));
create policy meta_preco_mercado_insert_tenant on public.meta_preco_mercado for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy meta_preco_mercado_update_tenant on public.meta_preco_mercado for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy meta_preco_mercado_delete_tenant on public.meta_preco_mercado for delete to authenticated using (public.tenant_ok(cliente_id));
create policy meta_preco_mercado_status_select_tenant on public.meta_preco_mercado_status for select to authenticated using (public.tenant_ok(cliente_id));
create policy meta_preco_mercado_status_insert_tenant on public.meta_preco_mercado_status for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy meta_preco_mercado_status_update_tenant on public.meta_preco_mercado_status for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy meta_preco_mercado_status_delete_tenant on public.meta_preco_mercado_status for delete to authenticated using (public.tenant_ok(cliente_id));
create policy meta_projetos_investimento_select_tenant on public.meta_projetos_investimento for select to authenticated using (public.tenant_ok(cliente_id));
create policy meta_projetos_investimento_insert_tenant on public.meta_projetos_investimento for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy meta_projetos_investimento_update_tenant on public.meta_projetos_investimento for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy meta_projetos_investimento_delete_tenant on public.meta_projetos_investimento for delete to authenticated using (public.tenant_ok(cliente_id));
create policy meta_valor_rebanho_precos_select_tenant on public.meta_valor_rebanho_precos for select to authenticated using (public.tenant_ok(cliente_id));
create policy meta_valor_rebanho_precos_insert_tenant on public.meta_valor_rebanho_precos for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy meta_valor_rebanho_precos_update_tenant on public.meta_valor_rebanho_precos for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy meta_valor_rebanho_precos_delete_tenant on public.meta_valor_rebanho_precos for delete to authenticated using (public.tenant_ok(cliente_id));
create policy meta_valor_rebanho_status_select_tenant on public.meta_valor_rebanho_status for select to authenticated using (public.tenant_ok(cliente_id));
create policy meta_valor_rebanho_status_insert_tenant on public.meta_valor_rebanho_status for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy meta_valor_rebanho_status_update_tenant on public.meta_valor_rebanho_status for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy meta_valor_rebanho_status_delete_tenant on public.meta_valor_rebanho_status for delete to authenticated using (public.tenant_ok(cliente_id));
create policy meta_versoes_select_tenant on public.meta_versoes for select to authenticated using (public.tenant_ok(cliente_id));
create policy meta_versoes_insert_tenant on public.meta_versoes for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy meta_versoes_update_tenant on public.meta_versoes for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy meta_versoes_delete_tenant on public.meta_versoes for delete to authenticated using (public.tenant_ok(cliente_id));
create policy pasto_movimentacoes_select_tenant on public.pasto_movimentacoes for select to authenticated using (public.tenant_ok(cliente_id));
create policy pasto_movimentacoes_insert_tenant on public.pasto_movimentacoes for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy pasto_movimentacoes_update_tenant on public.pasto_movimentacoes for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy pasto_movimentacoes_delete_tenant on public.pasto_movimentacoes for delete to authenticated using (public.tenant_ok(cliente_id));
create policy pastos_select_tenant on public.pastos for select to authenticated using (public.tenant_ok(cliente_id));
create policy pastos_insert_tenant on public.pastos for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy pastos_update_tenant on public.pastos for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy pastos_delete_tenant on public.pastos for delete to authenticated using (public.tenant_ok(cliente_id));
create policy planejamento_area_meta_select_tenant on public.planejamento_area_meta for select to authenticated using (public.tenant_ok(cliente_id));
create policy planejamento_area_meta_insert_tenant on public.planejamento_area_meta for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy planejamento_area_meta_update_tenant on public.planejamento_area_meta for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy planejamento_area_meta_delete_tenant on public.planejamento_area_meta for delete to authenticated using (public.tenant_ok(cliente_id));
create policy planejamento_financeiro_select_tenant on public.planejamento_financeiro for select to authenticated using (public.tenant_ok(cliente_id));
create policy planejamento_financeiro_insert_tenant on public.planejamento_financeiro for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy planejamento_financeiro_update_tenant on public.planejamento_financeiro for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy planejamento_financeiro_delete_tenant on public.planejamento_financeiro for delete to authenticated using (public.tenant_ok(cliente_id));
create policy preco_mercado_select_tenant on public.preco_mercado for select to authenticated using (public.tenant_ok(cliente_id));
create policy preco_mercado_insert_tenant on public.preco_mercado for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy preco_mercado_update_tenant on public.preco_mercado for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy preco_mercado_delete_tenant on public.preco_mercado for delete to authenticated using (public.tenant_ok(cliente_id));
create policy preco_mercado_status_select_tenant on public.preco_mercado_status for select to authenticated using (public.tenant_ok(cliente_id));
create policy preco_mercado_status_insert_tenant on public.preco_mercado_status for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy preco_mercado_status_update_tenant on public.preco_mercado_status for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy preco_mercado_status_delete_tenant on public.preco_mercado_status for delete to authenticated using (public.tenant_ok(cliente_id));
create policy saldos_iniciais_select_tenant on public.saldos_iniciais for select to authenticated using (public.tenant_ok(cliente_id));
create policy saldos_iniciais_insert_tenant on public.saldos_iniciais for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy saldos_iniciais_update_tenant on public.saldos_iniciais for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy saldos_iniciais_delete_tenant on public.saldos_iniciais for delete to authenticated using (public.tenant_ok(cliente_id));
create policy valor_rebanho_fechamento_select_tenant on public.valor_rebanho_fechamento for select to authenticated using (public.tenant_ok(cliente_id));
create policy valor_rebanho_fechamento_insert_tenant on public.valor_rebanho_fechamento for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy valor_rebanho_fechamento_update_tenant on public.valor_rebanho_fechamento for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy valor_rebanho_fechamento_delete_tenant on public.valor_rebanho_fechamento for delete to authenticated using (public.tenant_ok(cliente_id));
create policy valor_rebanho_fechamento_itens_select_tenant on public.valor_rebanho_fechamento_itens for select to authenticated using (public.tenant_ok(cliente_id));
create policy valor_rebanho_fechamento_itens_insert_tenant on public.valor_rebanho_fechamento_itens for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy valor_rebanho_fechamento_itens_update_tenant on public.valor_rebanho_fechamento_itens for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy valor_rebanho_fechamento_itens_delete_tenant on public.valor_rebanho_fechamento_itens for delete to authenticated using (public.tenant_ok(cliente_id));
create policy valor_rebanho_mensal_select_tenant on public.valor_rebanho_mensal for select to authenticated using (public.tenant_ok(cliente_id));
create policy valor_rebanho_mensal_insert_tenant on public.valor_rebanho_mensal for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy valor_rebanho_mensal_update_tenant on public.valor_rebanho_mensal for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy valor_rebanho_mensal_delete_tenant on public.valor_rebanho_mensal for delete to authenticated using (public.tenant_ok(cliente_id));
create policy valor_rebanho_meta_select_tenant on public.valor_rebanho_meta for select to authenticated using (public.tenant_ok(cliente_id));
create policy valor_rebanho_meta_insert_tenant on public.valor_rebanho_meta for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy valor_rebanho_meta_update_tenant on public.valor_rebanho_meta for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy valor_rebanho_meta_delete_tenant on public.valor_rebanho_meta for delete to authenticated using (public.tenant_ok(cliente_id));
create policy valor_rebanho_meta_validada_select_tenant on public.valor_rebanho_meta_validada for select to authenticated using (public.tenant_ok(cliente_id));
create policy valor_rebanho_meta_validada_insert_tenant on public.valor_rebanho_meta_validada for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy valor_rebanho_meta_validada_update_tenant on public.valor_rebanho_meta_validada for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy valor_rebanho_meta_validada_delete_tenant on public.valor_rebanho_meta_validada for delete to authenticated using (public.tenant_ok(cliente_id));
create policy valor_rebanho_realizado_validado_select_tenant on public.valor_rebanho_realizado_validado for select to authenticated using (public.tenant_ok(cliente_id));
create policy valor_rebanho_realizado_validado_insert_tenant on public.valor_rebanho_realizado_validado for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy valor_rebanho_realizado_validado_update_tenant on public.valor_rebanho_realizado_validado for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy valor_rebanho_realizado_validado_delete_tenant on public.valor_rebanho_realizado_validado for delete to authenticated using (public.tenant_ok(cliente_id));
create policy zoot_importacoes_select_tenant on public.zoot_importacoes for select to authenticated using (public.tenant_ok(cliente_id));
create policy zoot_importacoes_insert_tenant on public.zoot_importacoes for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy zoot_importacoes_update_tenant on public.zoot_importacoes for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy zoot_importacoes_delete_tenant on public.zoot_importacoes for delete to authenticated using (public.tenant_ok(cliente_id));
create policy zoot_mensal_cache_select_tenant on public.zoot_mensal_cache for select to authenticated using (public.tenant_ok(cliente_id));
create policy zoot_mensal_cache_insert_tenant on public.zoot_mensal_cache for insert to authenticated with check (public.tenant_ok(cliente_id));
create policy zoot_mensal_cache_update_tenant on public.zoot_mensal_cache for update to authenticated using (public.tenant_ok(cliente_id)) with check (public.tenant_ok(cliente_id));
create policy zoot_mensal_cache_delete_tenant on public.zoot_mensal_cache for delete to authenticated using (public.tenant_ok(cliente_id));
create policy bancos_referencia_select_tenant on public.bancos_referencia for select to authenticated using (true);
create policy bancos_referencia_insert_tenant on public.bancos_referencia for insert to authenticated with check (public.is_admin_agroinblue((select auth.uid())));
create policy bancos_referencia_update_tenant on public.bancos_referencia for update to authenticated using (public.is_admin_agroinblue((select auth.uid()))) with check (public.is_admin_agroinblue((select auth.uid())));
create policy bancos_referencia_delete_tenant on public.bancos_referencia for delete to authenticated using (public.is_admin_agroinblue((select auth.uid())));
create policy categorias_select_tenant on public.categorias for select to authenticated using (true);
create policy categorias_insert_tenant on public.categorias for insert to authenticated with check (public.is_admin_agroinblue((select auth.uid())));
create policy categorias_update_tenant on public.categorias for update to authenticated using (public.is_admin_agroinblue((select auth.uid()))) with check (public.is_admin_agroinblue((select auth.uid())));
create policy categorias_delete_tenant on public.categorias for delete to authenticated using (public.is_admin_agroinblue((select auth.uid())));
create policy categorias_rebanho_select_tenant on public.categorias_rebanho for select to authenticated using (true);
create policy categorias_rebanho_insert_tenant on public.categorias_rebanho for insert to authenticated with check (public.is_admin_agroinblue((select auth.uid())));
create policy categorias_rebanho_update_tenant on public.categorias_rebanho for update to authenticated using (public.is_admin_agroinblue((select auth.uid()))) with check (public.is_admin_agroinblue((select auth.uid())));
create policy categorias_rebanho_delete_tenant on public.categorias_rebanho for delete to authenticated using (public.is_admin_agroinblue((select auth.uid())));
create policy zoo_componentes_financeiros_select_tenant on public.zoo_componentes_financeiros for select to authenticated using (true);
create policy zoo_componentes_financeiros_insert_tenant on public.zoo_componentes_financeiros for insert to authenticated with check (public.is_admin_agroinblue((select auth.uid())));
create policy zoo_componentes_financeiros_update_tenant on public.zoo_componentes_financeiros for update to authenticated using (public.is_admin_agroinblue((select auth.uid()))) with check (public.is_admin_agroinblue((select auth.uid())));
create policy zoo_componentes_financeiros_delete_tenant on public.zoo_componentes_financeiros for delete to authenticated using (public.is_admin_agroinblue((select auth.uid())));
create policy profiles_select_tenant on public.profiles for select to authenticated using (user_id = (select auth.uid()) or public.is_admin_agroinblue((select auth.uid())));
create policy profiles_insert_tenant on public.profiles for insert to authenticated with check (user_id = (select auth.uid()));
create policy profiles_update_tenant on public.profiles for update to authenticated using (user_id = (select auth.uid()) or public.is_admin_agroinblue((select auth.uid()))) with check (user_id = (select auth.uid()) or public.is_admin_agroinblue((select auth.uid())));
create policy profiles_delete_tenant on public.profiles for delete to authenticated using (public.is_admin_agroinblue((select auth.uid())));
create policy fechamento_pasto_itens_select_tenant on public.fechamento_pasto_itens for select to authenticated using (public.tenant_ok((select p.cliente_id from public.fechamento_pastos p where p.id = fechamento_id)));
create policy fechamento_pasto_itens_insert_tenant on public.fechamento_pasto_itens for insert to authenticated with check (public.tenant_ok((select p.cliente_id from public.fechamento_pastos p where p.id = fechamento_id)));
create policy fechamento_pasto_itens_update_tenant on public.fechamento_pasto_itens for update to authenticated using (public.tenant_ok((select p.cliente_id from public.fechamento_pastos p where p.id = fechamento_id))) with check (public.tenant_ok((select p.cliente_id from public.fechamento_pastos p where p.id = fechamento_id)));
create policy fechamento_pasto_itens_delete_tenant on public.fechamento_pasto_itens for delete to authenticated using (public.tenant_ok((select p.cliente_id from public.fechamento_pastos p where p.id = fechamento_id)));
create policy mesa_ofx_validacao_select_tenant on public.mesa_ofx_validacao for select to authenticated using (public.tenant_ok((select p.cliente_id from public.mesa_sessao p where p.id = sessao_id)));
create policy mesa_ofx_validacao_insert_tenant on public.mesa_ofx_validacao for insert to authenticated with check (public.tenant_ok((select p.cliente_id from public.mesa_sessao p where p.id = sessao_id)));
create policy mesa_ofx_validacao_update_tenant on public.mesa_ofx_validacao for update to authenticated using (public.tenant_ok((select p.cliente_id from public.mesa_sessao p where p.id = sessao_id))) with check (public.tenant_ok((select p.cliente_id from public.mesa_sessao p where p.id = sessao_id)));
create policy mesa_ofx_validacao_delete_tenant on public.mesa_ofx_validacao for delete to authenticated using (public.tenant_ok((select p.cliente_id from public.mesa_sessao p where p.id = sessao_id)));
create policy mesa_par_select_tenant on public.mesa_par for select to authenticated using (public.tenant_ok((select p.cliente_id from public.mesa_sessao p where p.id = sessao_id)));
create policy mesa_par_insert_tenant on public.mesa_par for insert to authenticated with check (public.tenant_ok((select p.cliente_id from public.mesa_sessao p where p.id = sessao_id)));
create policy mesa_par_update_tenant on public.mesa_par for update to authenticated using (public.tenant_ok((select p.cliente_id from public.mesa_sessao p where p.id = sessao_id))) with check (public.tenant_ok((select p.cliente_id from public.mesa_sessao p where p.id = sessao_id)));
create policy mesa_par_delete_tenant on public.mesa_par for delete to authenticated using (public.tenant_ok((select p.cliente_id from public.mesa_sessao p where p.id = sessao_id)));
create policy reclassificacoes_select_tenant on public.reclassificacoes for select to authenticated using (public.tenant_ok((select p.cliente_id from public.fazendas p where p.id = fazenda_id)));
create policy reclassificacoes_insert_tenant on public.reclassificacoes for insert to authenticated with check (public.tenant_ok((select p.cliente_id from public.fazendas p where p.id = fazenda_id)));
create policy reclassificacoes_update_tenant on public.reclassificacoes for update to authenticated using (public.tenant_ok((select p.cliente_id from public.fazendas p where p.id = fazenda_id))) with check (public.tenant_ok((select p.cliente_id from public.fazendas p where p.id = fazenda_id)));
create policy reclassificacoes_delete_tenant on public.reclassificacoes for delete to authenticated using (public.tenant_ok((select p.cliente_id from public.fazendas p where p.id = fazenda_id)));
create policy valor_rebanho_meta_itens_select_tenant on public.valor_rebanho_meta_itens for select to authenticated using (public.tenant_ok((select p.cliente_id from public.valor_rebanho_meta p where p.id = meta_id)));
create policy valor_rebanho_meta_itens_insert_tenant on public.valor_rebanho_meta_itens for insert to authenticated with check (public.tenant_ok((select p.cliente_id from public.valor_rebanho_meta p where p.id = meta_id)));
create policy valor_rebanho_meta_itens_update_tenant on public.valor_rebanho_meta_itens for update to authenticated using (public.tenant_ok((select p.cliente_id from public.valor_rebanho_meta p where p.id = meta_id))) with check (public.tenant_ok((select p.cliente_id from public.valor_rebanho_meta p where p.id = meta_id)));
create policy valor_rebanho_meta_itens_delete_tenant on public.valor_rebanho_meta_itens for delete to authenticated using (public.tenant_ok((select p.cliente_id from public.valor_rebanho_meta p where p.id = meta_id)));
create policy pasto_condicoes_select_tenant on public.pasto_condicoes for select to authenticated using (public.tenant_ok((select p.cliente_id from public.pastos p where p.id = pasto_id)));
create policy pasto_condicoes_insert_tenant on public.pasto_condicoes for insert to authenticated with check (public.tenant_ok((select p.cliente_id from public.pastos p where p.id = pasto_id)));
create policy pasto_condicoes_update_tenant on public.pasto_condicoes for update to authenticated using (public.tenant_ok((select p.cliente_id from public.pastos p where p.id = pasto_id))) with check (public.tenant_ok((select p.cliente_id from public.pastos p where p.id = pasto_id)));
create policy pasto_condicoes_delete_tenant on public.pasto_condicoes for delete to authenticated using (public.tenant_ok((select p.cliente_id from public.pastos p where p.id = pasto_id)));
create policy pasto_geometrias_select_tenant on public.pasto_geometrias for select to authenticated using (public.tenant_ok((select p.cliente_id from public.pastos p where p.id = pasto_id)));
create policy pasto_geometrias_insert_tenant on public.pasto_geometrias for insert to authenticated with check (public.tenant_ok((select p.cliente_id from public.pastos p where p.id = pasto_id)));
create policy pasto_geometrias_update_tenant on public.pasto_geometrias for update to authenticated using (public.tenant_ok((select p.cliente_id from public.pastos p where p.id = pasto_id))) with check (public.tenant_ok((select p.cliente_id from public.pastos p where p.id = pasto_id)));
create policy pasto_geometrias_delete_tenant on public.pasto_geometrias for delete to authenticated using (public.tenant_ok((select p.cliente_id from public.pastos p where p.id = pasto_id)));
create policy boitel_planejamento_historico_select_tenant on public.boitel_planejamento_historico for select to authenticated using (public.tenant_ok((select p.cliente_id from public.boitel_planejamento p where p.id = planejamento_id)));
create policy boitel_planejamento_historico_insert_tenant on public.boitel_planejamento_historico for insert to authenticated with check (public.tenant_ok((select p.cliente_id from public.boitel_planejamento p where p.id = planejamento_id)));
create policy boitel_planejamento_historico_update_tenant on public.boitel_planejamento_historico for update to authenticated using (public.tenant_ok((select p.cliente_id from public.boitel_planejamento p where p.id = planejamento_id))) with check (public.tenant_ok((select p.cliente_id from public.boitel_planejamento p where p.id = planejamento_id)));
create policy boitel_planejamento_historico_delete_tenant on public.boitel_planejamento_historico for delete to authenticated using (public.tenant_ok((select p.cliente_id from public.boitel_planejamento p where p.id = planejamento_id)));
create policy preco_mercado_ajuste_select_tenant on public.preco_mercado_ajuste for select to authenticated using (public.tenant_ok((select p.cliente_id from public.preco_mercado p where p.id = preco_id)));
create policy preco_mercado_ajuste_insert_tenant on public.preco_mercado_ajuste for insert to authenticated with check (public.tenant_ok((select p.cliente_id from public.preco_mercado p where p.id = preco_id)));
create policy preco_mercado_ajuste_update_tenant on public.preco_mercado_ajuste for update to authenticated using (public.tenant_ok((select p.cliente_id from public.preco_mercado p where p.id = preco_id))) with check (public.tenant_ok((select p.cliente_id from public.preco_mercado p where p.id = preco_id)));
create policy preco_mercado_ajuste_delete_tenant on public.preco_mercado_ajuste for delete to authenticated using (public.tenant_ok((select p.cliente_id from public.preco_mercado p where p.id = preco_id)));
create policy zoot_importacoes_staging_select_tenant on public.zoot_importacoes_staging for select to authenticated using (public.tenant_ok((select p.cliente_id from public.zoot_importacoes p where p.id = importacao_id)));
create policy zoot_importacoes_staging_insert_tenant on public.zoot_importacoes_staging for insert to authenticated with check (public.tenant_ok((select p.cliente_id from public.zoot_importacoes p where p.id = importacao_id)));
create policy zoot_importacoes_staging_update_tenant on public.zoot_importacoes_staging for update to authenticated using (public.tenant_ok((select p.cliente_id from public.zoot_importacoes p where p.id = importacao_id))) with check (public.tenant_ok((select p.cliente_id from public.zoot_importacoes p where p.id = importacao_id)));
create policy zoot_importacoes_staging_delete_tenant on public.zoot_importacoes_staging for delete to authenticated using (public.tenant_ok((select p.cliente_id from public.zoot_importacoes p where p.id = importacao_id)));
